export const drums = {
	rock: {
		65: { wav: "kick", name: "kick" },
		83: { wav: "kick2", name: "kick 2" },
		68: { wav: "snare", name: "snare" },
		70: { wav: "roll", name: "roll" },
		71: { wav: "floorTom", name: "floor tom" },
		72: { wav: "closedHat", name: "closed hat" },
		74: { wav: "openHat", name: "open hat" },
		75: { wav: "crash", name: "crash" },
		76: { wav: "ride", name: "ride" },
	},
	jazz: {
		65: { wav: "kick", name: "kick" },
		83: { wav: "snare", name: "snare" },
		68: { wav: "flam", name: "flam" },
		70: { wav: "closedHat", name: "closed hat" },
		71: { wav: "openHat", name: "open hat" },
		72: { wav: "ride1", name: "ride 1" },
		74: { wav: "ride2", name: "ride 2" },
		75: { wav: "rake", name: "rake" },
		76: { wav: "crash", name: "crash" },
	},
	hipHop: {
		65: { wav: "kick", name: "kick" },
		83: { wav: "kick", name: "kick 2" },
		68: { wav: "snare", name: "snare " },
		70: { wav: "roll", name: "roll" },
		71: { wav: "bongo", name: "bongo" },
		72: { wav: "closedHat", name: "closed hat" },
		74: { wav: "openHat", name: "open hat" },
		75: { wav: "crash", name: "crash" },
		76: { wav: "ride", name: "ride" },
	},
};
